name: Tests

on: [push, pull_request]

jobs:
  tox:
    strategy:
      matrix:
        python-version:
          [
            "2.7",
            "3.5",
            "3.6",
            "3.7",
            "3.8",
            "3.9",
            "pypy-2.7",
            "pypy-3.6",
            "pypy-3.7",
          ]

    name: "Test for: ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox tox-gh-actions
      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: python -m tox
